name: Build and Run WebAssembly

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Execute using Makefile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - uses: oven-sh/setup-bun@v2
        with:
            bun-version: latest

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: (Fallback) Switch to Rust nightly if needed
        if: failure()
        run: |
          echo "Switching to Rust nightly toolchain..."
          rustup install nightly
          rustup override set nightly
          rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run Tests and Benchmarks
        run: make bench
